version: '3'
services:
  lounge:
    image: thelounge/thelounge:3.0.0-pre.7
    container_name: thelounge
    restart: always
    expose:
      - 9000
    volumes:
      - data:/var/opt/thelounge
    networks:
      - web
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:irc.brooks.network"

volumes:
  data:

networks:
  web:
    external: true
