turn_on_art_lamp:
  sequence:
  - action: remote.send_command
    metadata: {}
    target:
      entity_id: remote.universal_remote
    data:
      device: art_lamp
      command: power_on
  alias: Turn on art lamp
  description: ''
  mode: single
turn_off_art_lamp:
  sequence:
  - action: remote.send_command
    metadata: {}
    target:
      entity_id: remote.universal_remote
    data:
      device: art_lamp
      command: power_off
  alias: Turn off art lamp
  description: ''
  mode: single
increase_brightness_of_art_lamp:
  sequence:
  - action: remote.send_command
    metadata: {}
    target:
      entity_id: remote.universal_remote
    data:
      device: art_lamp
      command: increase_brightness
  alias: Increase brightness of art lamp
  description: ''
  mode: single
decrease_brightness_of_art_lamp:
  sequence:
  - action: remote.send_command
    metadata: {}
    target:
      entity_id: remote.universal_remote
    data:
      device: art_lamp
      command: decrease_brightness
  alias: Decrease brightness of art lamp
  description: ''
  mode: single
increase_color_temperature_of_art_lamp:
  sequence:
  - action: remote.send_command
    metadata: {}
    target:
      entity_id: remote.universal_remote
    data:
      device: art_lamp
      command: increase_warmth
  alias: Increase color temperature of art lamp
  description: ''
  mode: single


toggle_kitchen_light:
  sequence:
  - action: remote.send_command
    metadata: {}
    target:
      entity_id: remote.universal_remote
    data:
      device: kitchen_light
      command: power
  alias: Toggle kitchen light
  description: ''
  mode: single
increase_brightness_of_kitchen_light:
  sequence:
  - action: remote.send_command
    metadata: {}
    target:
      entity_id: remote.universal_remote
    data:
      device: kitchen_light
      command: increase_brightness
  alias: Increase brightness of kitchen light
  description: ''
  mode: single
decrease_brightness_of_kitchen_light:
  sequence:
  - action: remote.send_command
    metadata: {}
    target:
      entity_id: remote.universal_remote
    data:
      device: kitchen_light
      command: decrease_brightness
  alias: Decrease brightness of kitchen light
  description: ''
  mode: single
