version: '3'

services:
  homeassistant:
    image: 'ghcr.io/home-assistant/home-assistant:stable'
    container_name: homeassistant
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - config:/config
      - ./config/configuration.yaml:/config/configuration.yaml
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1

volumes:
  config:
