services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    expose:
      - 3000
    volumes:
      - data:/var/lib/grafana
      - config:/etc/grafana
    networks:
      - web
      - metrics
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=web'
      - 'traefik.http.routers.grafana.rule=Host(`graphs.cabin.brooks.network`)'
      - 'traefik.http.routers.grafana.entrypoints=websecure'
      - 'traefik.http.routers.grafana.tls.certresolver=letsencrypt'

volumes:
  data:
  config:

networks:
  metrics:
    external: true
  web:
    external: true
