version: '3'

services:
  homebridge:
    image: oznu/homebridge
    container_name: homebridge
    restart: always
    network_mode: host
    volumes:
      - config:/homebridge
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581

volumes:
  config:
