debug = false

logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[accessLog]

[metrics]
  [metrics.prometheus]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "brooks.network"
watch = true
exposedByDefault = false

[acme]
email = "bswinnerton@gmail.com"
storage="/etc/traefik/acme/acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
